server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 支援 Vue Router History 模式，避免重新整理 404
        try_files $uri $uri/ /index.html;
    }

    # 快取前端靜態資源
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root    /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
