import {
  Cpu,
  Flag,
  IceDrink,
  Monitor,
  Odometer,
  Van,
  VideoCameraFilled,
  Brush,
  Star,
  Present,
  Compass,
  Timer,
  GoodsFilled,
  House,
  Connection,
  Calendar,
  Sell,
  MagicStick,
} from '@element-plus/icons-vue'
import { ROLES } from '@/domains/auth/constants/userConstants'

const ALL_ROLES = [ROLES.GUEST, ROLES.USER, ROLES.ADMIN]
const LOGGED_IN_ROLES = [ROLES.USER, ROLES.ADMIN]

export const NAVIGATION_SCHEMA = [
  {
    type: 'button',
    key: 'news',
    label: '最新消息',
    route: { name: 'news' },
    roles: ALL_ROLES,
    usage: ['sidebar'],
  },
  {
    type: 'button',
    key: 'about',
    label: '關於我們',
    route: { name: 'about' },
    roles: ALL_ROLES,
    usage: ['sidebar'],
  },
  {
    type: 'button',
    key: 'home',
    label: '回首頁',
    route: { name: 'home' },
    roles: ALL_ROLES,
    usage: ['sidebar'],
  },
  {
    type: 'button',
    key: 'shoppingGuide',
    label: '購買須知',
    route: { name: 'shoppingGuide' },
    roles: ALL_ROLES,
    usage: ['sidebar'],
  },
  {
    type: 'button',
    key: 'qa',
    label: '常見問題 Q&A',
    route: { name: 'qa' },
    roles: ALL_ROLES,
    usage: ['sidebar'],
  },
  {
    type: 'dropdown',
    key: 'productMenu',
    label: '商品選單',
    icon: Sell,
    roles: ALL_ROLES,
    usage: ['sidebar'],
    subs: [
      { label: '商品總覽', route: { name: 'overview' }, roles: ALL_ROLES },
      { label: '商品管理', route: { name: 'productManage' }, roles: LOGGED_IN_ROLES },
    ],
  },
  {
    type: 'dropdown',
    key: 'doubleeleven',
    label: '雙11週年盛典',
    icon: Odometer,
    roles: ALL_ROLES,
    usage: ['sidebar', 'topbar'],
    subs: [
      { label: '年度特選回饋', route: { name: 'rewards' } },
      { label: '滿額加碼驚喜', route: { name: 'gifts' } },
    ],
  },
  {
    type: 'dropdown',
    key: 'event',
    label: '活動專區',
    icon: Calendar,
    roles: ALL_ROLES,
    usage: ['sidebar', 'topbar'],
    subs: [
      { label: '本週特惠', route: { name: 'flashSale' } },
      { label: '幸運拉霸機', route: { name: 'luckySlot' } },
    ],
  },
  {
    type: 'dropdown',
    key: 'crossover',
    label: '聯名專區',
    icon: Connection,
    roles: ALL_ROLES,
    usage: ['sidebar', 'topbar'],
    subs: [
      { label: '動漫聯名款', route: { name: 'crossover', params: { type: 'anime' } } },
      { label: '電影大聯盟', route: { name: 'crossover', params: { type: 'movie' } } },
      { label: '設計師聯名款', route: { name: 'crossover', params: { type: 'designer' } } },
      { label: '全球限量版', route: { name: 'crossover', params: { type: 'limited' } } },
    ],
  },
  {
    type: 'dropdown',
    key: 'brands',
    label: '品牌專區',
    icon: GoodsFilled,
    roles: ALL_ROLES,
    usage: ['sidebar', 'topbar'],
    subs: [
      { label: '3C 數位', route: { name: 'brand', params: { type: 'electronics' } } },
      { label: '服飾配件', route: { name: 'brand', params: { type: 'apparel' } } },
      { label: '食品飲品', route: { name: 'brand', params: { type: 'food' } } },
      { label: '汽機車用品', route: { name: 'brand', params: { type: 'vehicle' } } },
      { label: '居家生活', route: { name: 'brand', params: { type: 'lifeStyle' } } },
    ],
  },
  {
    type: 'dropdown',
    key: 'seasonal',
    label: '季節限定',
    icon: Van,
    roles: ALL_ROLES,
    usage: ['sidebar', 'topbar'],
    subs: [
      { label: '季節精選', route: { name: 'seasonalFeatured' } },
      { label: '出遊推薦', route: { name: 'travelPicks' } },
    ],
  },

  {
    type: 'button',
    label: '最新消息',
    route: { name: 'news' },
    roles: ALL_ROLES,
    usage: ['topbar'],
  },
  {
    type: 'button',
    label: '購買須知',
    route: { name: 'shoppingGuide' },
    roles: ALL_ROLES,
    usage: ['topbar'],
  },
]
